
package com.example.testclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-01-25T14:03:58.851+03:00
 * Generated source version: 3.5.5
 *
 */
public final class TestService_TestServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.example.com/", "Tester");

    private TestService_TestServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Tester.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        Tester ss = new Tester(wsdlURL, SERVICE_NAME);
        TestService port = ss.getTestServicePort();

        {
        System.out.println("Invoking sendPerson...");
        java.lang.String _sendPerson_arg0 = "";
        java.lang.String _sendPerson_arg1 = "";
        int _sendPerson_arg2 = 0;
        com.example.testclient.Person _sendPerson__return = port.sendPerson(_sendPerson_arg0, _sendPerson_arg1, _sendPerson_arg2);
        System.out.println("sendPerson.result=" + _sendPerson__return);


        }

        System.exit(0);
    }

}
